SET NAMES 'UTF8MB4';
DROP DATABASE IF EXIST tacos;
CREATE DATABASE IF NOT EXIST tacos DEFAULT CHARACTER ST UTF8MB4;

USE tacos;

CREATE TABLE usuario(
    id_uso INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(30) NOT NULL,
    apellido VARCHAR(30) NOT NULL,
    PRIMARY KEY (id_uso)
) DEFAULT CHARACTER SET UTF8MB4